services:
  # backend-app:
  #   build: .
  #   command: npm run start:prod
  #   ports:
  #     - '${PORT:-4000}:4000'
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - node_modules:/app/node_modules:delegated
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   networks:
  #     - app

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - '${FORWARD_DB_PORT:-27017}:27017'
    networks:
      - app
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app:
    driver: bridge

volumes:
  node_modules: